### ISSUE TITLE
Cannot use /openinv on Spigot 1.21.10

### ISSUE THREAD

**Issue by Nburi** [Jikoo/OpenInv#340]
`/oi` does not work in spigot 1.21.10 (`/oe`works)

here's the stack trace:
```[OpenInv] Task #789 for OpenInv v5.1.14 generated an exception
java.lang.NoSuchMethodError: 'void com.lishid.openinv.internal.reobf.container.bukkit.OpenPlayerInventory.<init>(com.lishid.openinv.internal.reobf.container.BaseOpenInventory)'
	at com.lishid.openinv.internal.reobf.container.bukkit.OpenPlayerInventorySelf.<init>(OpenPlayerInventorySelf.java:12) ~[?:?]
	at com.lishid.openinv.internal.reobf.container.menu.OpenInventoryMenu.createBukkitEntity(OpenInventoryMenu.java:107) ~[?:?]
	at com.lishid.openinv.internal.reobf.container.menu.OpenChestMenu.getBukkitView(OpenChestMenu.java:143) ~[?:?]
	at com.lishid.openinv.internal.reobf.container.menu.OpenChestMenu.getBukkitView(OpenChestMenu.java:40) ~[?:?]
	at net.minecraft.world.inventory.Container.transferTo(Container.java:89) ~[spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at org.bukkit.craftbukkit.v1_21_R6.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1314) ~[spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at com.lishid.openinv.internal.reobf.player.PlayerManager.openInventory(PlayerManager.java:222) ~[?:?]
	at com.lishid.openinv.util.InternalAccessor.openInventory(InternalAccessor.java:261) ~[?:?]
	at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:260) ~[?:?]
	at com.lishid.openinv.command.OpenInvCommand.handle(OpenInvCommand.java:175) ~[?:?]
	at com.lishid.openinv.command.PlayerLookupCommand$1$1.run(PlayerLookupCommand.java:85) ~[?:?]
	at org.bukkit.craftbukkit.v1_21_R6.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at org.bukkit.craftbukkit.v1_21_R6.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1537) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1426) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at net.minecraft.server.dedicated.DedicatedServer.a(DedicatedServer.java:432) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:1127) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:337) [spigot-1.21.10-R0.1-SNAPSHOT.jar:4541-Spigot-6e369ba-aa5381f]
	at java.base/java.lang.Thread.run(Thread.java:1447) [?:?]```
